services:
  hams:
    build:
        context: ./Hospital OPD & Appointment Management System (HAMS)
        dockerfile: Dockerfile
    ports:
        - "8080:8080"
        - "8081:8081"
    depends_on:
        - sql-server
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
    networks:
        - hams-network
    restart: 
        on-failure
    
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
        SA_PASSWORD: "Password12345!"
        ACCEPT_EULA: "Y"
    ports:
    - "1433:1433"
    volumes:
    - sqlvolume:/var/opt/mssql
    networks:
    - hams-network
    restart: always
 
networks:
    hams-network:
    
volumes:
    sqlvolume: